app/__init__.py
from flask import Flask
from database.database_creator import db
from flask_login import LoginManager
from database.database_creator import User


def create_app():
    app = Flask(__name__)
    app.config["SECRET_KEY"] = "very_secret_key"
    app.config["SECURITY_PASSWORD_SALT"] = "very_very_secret_key"
    app.config["SESSION_PERMANENT"] = False
    app.config["SESSION_TYPE"] = "filesystem"
    app.config["SQLALCHEMY_DATABASE_URI"] = "sqlite:///chat-database.sqlite3"
    db.init_app(app)

    with app.app_context():
        db.create_all()

    login_manager = LoginManager()
    login_manager.login_view = "auth.login"
    login_manager.init_app(app)

    @login_manager.user_loader
    def load_user(user_id):
        return User.query.get(int(user_id))

    from . import routes
    from . import auth_routes

    app.register_blueprint(routes.main_bp)
    app.register_blueprint(auth_routes.auth_bp)

    from .events import socketio

    socketio.init_app(app)

    return app

app/routes.py
from flask import Blueprint, render_template, request, session, redirect, url_for
from flask_login import current_user
from . import scripts
from database import database_inquiries, data_loader
from .auth_routes import login_required

main_bp = Blueprint("main", __name__)


@main_bp.route("/home", methods=["GET", "POST"])
@login_required
def home():
    session.pop("room_code", None)
    return render_template("home.html")


@main_bp.route("/join_room", methods=["GET", "POST"])
@login_required
def join_room():
    if request.method == "POST":
        room_code = request.form.get("room_code")
        username = current_user.username

        if room_code == "":
            room_code = scripts.generate_room_code(5)
            data_loader.load_room(room_data=room_code)
        elif database_inquiries.check_if_room_exist(room_code) is False:
            print(room_code)
            return render_template("join_room.html")

        session["room_code"] = room_code
        data_loader.load_user_to_room(
            room_data=room_code,
            user_data=username,
        )
        return redirect(url_for("main.chat"))

    return render_template(
        "join_room.html", recent_room_codes=scripts.rooms_to_codes(current_user.rooms)
    )


@main_bp.route("/create_room", methods=["GET"])
@login_required
def create_room():
    username = current_user.username
    room_code = scripts.generate_room_code(5)
    data_loader.load_room(room_data=room_code)

    session["room_code"] = room_code
    data_loader.load_user_to_room(
        room_data=room_code,
        user_data=username,
    )
    return redirect(url_for("main.chat"))


@main_bp.route("/chat")
@login_required
def chat():
    room_code = session.get("room_code")
    if database_inquiries.check_if_room_exist(room_code=room_code):
        return render_template(
            "chat.html",
            code=room_code,
            messages=(
                scripts.change_dict_format(
                    database_inquiries.find_all_messages_in_room(room_code=room_code)
                )
            ),
        )
    else:
        return redirect(url_for("main.join_room"))

app/templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta http-equiv="x-ua-compatible" content="ie=edge" />
    <title>Chat - {% block title %}{% endblock %}</title>
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css" rel="stylesheet" />
    <link href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap" rel="stylesheet" />
    <link href="https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/6.4.0/mdb.min.css" rel="stylesheet" />
    {% block style %}{% endblock %}
</head>

<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container-fluid">
        <a class="navbar-brand"><img src="{{ url_for('static', filename='chat_logo.png' ) }}" style="width:2rem;"></a>
        <button class="navbar-toggler" type="button" data-mdb-toggle="collapse" data-mdb-target="#navbarNav"
            aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <i class="fas fa-bars"></i>
        </button>
        {% block nav %}{% endblock %}
    </div>
</nav>

<body style="background-color: #eaeaea">
    {% block content %} {% endblock %}
</body>


<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/6.4.0/mdb.min.js"></script>

</html>

app/templates/chat.html
{% extends "base.html" %}

{% block title %} Chat {% endblock %}

{% block style %}
<link rel="stylesheet" href="{{ url_for('static', filename='chat_style.css') }}">
{% endblock %}


{% block nav %}
<div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
        <li class="nav-item">
            <a class="nav-link" aria-current="page" href="{{ url_for('main.home')}}">Home</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="{{ url_for('auth.logout') }}">Logout</a>
        </li>
    </ul>

</div>
{% endblock %}



{% block content %}
<script src="https://cdnjs.cloudflare.com/ajax/libs/socket.io/4.0.1/socket.io.js"
    integrity="sha512-q/dWJ3kcmjBLU4Qc47E4A9kTB4m3wuTY7vkFJDTZKjTs8jhyGQnaUrxa0Ytd0ssMZhbNua9hE+E7Qv1j+DyZwA=="
    crossorigin="anonymous"></script>

<div class="text-center">
    <h2 class="m-3">You're logged as <b>{{current_user.username}}</b> and your room id is:
        <b>{{session["room_code"]}}</b>
    </h2>
</div>

<div class="container" style="max-width: 50rem;">

    <div class="chatbox" id="chatbox">
        {% for message in messages %}
        <div class="message">
            <span class="username">{{ message.user }}: </span>
            <span class="content">{{ message.message }}</span>
            <span class="date">{{ message.date.strftime("%d.%m.%Y, %H:%M:%S") }}</span>
        </div>
        {% endfor %}
    </div>

    <form class="input-container" onsubmit="event.preventDefault(); sendMessage()">
        <div class="input-group">
            <input type="text" id="message-input" class="form-control" placeholder="Type your message..." autofocus>
            <button id="send-message-btn" class="btn btn-primary" type="submit">Send</button>
        </div>
    </form>
</div>

<script type="text/javascript" charset="utf-8">

    const socket = io();
    const chatbox = document.getElementById("chatbox");

    const addMessage = (user, message) => {
        const content = `
        <div class="message">
            <span class="username">${user}: </span>
            <span class="content">${message}</span>
            <span class="date">${new Date().toLocaleString()}</span>
        </div>

        `
        chatbox.innerHTML = content + chatbox.innerHTML
    }

    socket.on("message", (data) => {
        addMessage(data.user, data.message)
    })


    const sendMessage = () => {
        const message = document.getElementById("message-input");
        if (message.value.length === 0) {
            return;
        }
        socket.emit("message", { data: message.value });
        message.value = "";
    }

</script>




{% endblock %}

app/templates/home.html
{% extends "base.html" %}


{% block title %} Home{% endblock %}

{% block nav %}
<div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
        <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="{{ url_for('main.home')}}">Home</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="{{ url_for('auth.logout') }}">Logout</a>
        </li>
    </ul>

</div>
{% endblock %}



{% block content %}



{% with messages = get_flashed_messages(with_categories=true) %}
{% if messages %}

{% for category, message in messages %}
<div class="container" style="max-width: 40rem;">
    <div class="alert alert-{{ category }} mt-2" role="alert">{{ message }}</div>
</div>
{% endfor %}

{% endif %}
{% endwith %}



<div class="text-center">
    <h1 class="mb-6 p-5">Welcome, {{current_user.username}}</h1>
</div>

<div class="container">
    <div class="row justify-content-center">
        <div class="col-auto">
            <a href="{{url_for('main.join_room')}}">
                <button class="btn btn-primary" style="width:20rem; height:4rem;">Join a room</button>
            </a>
        </div>
        <div class="col-auto">
            <a href="{{url_for('main.create_room')}}">
                <button class="btn btn-success" style="width:20rem; height:4rem;">Create new room</button>
            </a>
        </div>
    </div>
</div>

{% endblock %}

app/templates/join_room.html
{% extends "base.html" %}


{% block title %} Login {% endblock %}

{% block nav %}
<div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
        <li class="nav-item">
            <a class="nav-link" aria-current="page" href="{{ url_for('main.home')}}">Home</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="{{ url_for('auth.logout') }}">Logout</a>
        </li>
    </ul>

</div>
{% endblock %}




{% block content %}

<div class="text-center">
    <h2 class="mb-3 p-5">Enter room code and join</h1>
</div>

<form method="post" class="container-fluid" style="max-width: 35rem;">

    <!-- room code -->
    <div class="form-outline mb-4 bg-light">
        <input type="text" id="room_code" name="room_code" class="form-control" />
        <label class="form-label" for="room_code">Room code</label>
    </div>

    <button type="submit" class="btn btn-success mb-4">Join</button>

    <div class="text-center">
        <p>Create a room instead: <a href="{{ url_for('main.create_room' ) }}">create</a></p>
    </div>
</form>

<div class="text-center">
    <h3 class="mb-3 p-5">Your previous rooms:</h3>
</div>

{% for room_code in recent_room_codes %}
<form class="input-container" method="post">
    <div class="container" style="max-width:20rem;">

        <div class="input-group mb-2">
            <input type="text" id="room_code" name="room_code" class="form-control" readonly value="{{ room_code }}">
            <button id="send-message-btn" class="btn btn-primary" type="submit">Join</button>
        </div>
    </div>
</form>

{% endfor %}




{% endblock %}

app/templates/login.html
{% extends "base.html" %}


{% block title %} Login {% endblock %}



{% block nav %}
<div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
        <li class="nav-item">
            <a class="nav-link disabled" aria-current="page" href="#">Home</a>
        </li>
        <li class="nav-item">
            <a class="nav-link disabled active" href="{{ url_for('auth.login') }}">Login</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="{{ url_for('auth.signup' )}}">Register</a>
        </li>
    </ul>
</div>
{% endblock %}


{% block content %}

{% with messages = get_flashed_messages(with_categories=true) %}
{% if messages %}

{% for category, message in messages %}
<div class="container" style="max-width: 40rem;">
    {% if category == "message" %}
    <div class="alert alert-danger mt-2" role="alert">{{ message }}</div>
    {% else %}
    <div class="alert alert-{{ category }} mt-2" role="alert">{{ message }}</div>
    {% endif %}
</div>
{% endfor %}

{% endif %}
{% endwith %}




<div class="text-center">
    <h2 class="mb-3 p-5">Login to start chatting!</h2>
</div>

<form method="post" class="container-fluid" style="max-width: 35rem;">

    <!-- login -->
    <div class="form-outline mb-4 bg-light">
        <input type="text" id="username" name="username" class="form-control" required />
        <label class="form-label" for="username">Login</label>
    </div>

    <!-- password -->
    <div class="form-outline mb-4 bg-light">
        <input type="password" id="password" name="password" class="form-control" required />
        <label class="form-label" for="password">Password</label>
    </div>

    <button type="submit" class="btn btn-primary btn-block mb-4">Sign in</button>

    <div class="text-center">
        <p>Not a member? <a href="{{ url_for('auth.signup' ) }}">Register</a></p>
    </div>
</form>

{% endblock %}

app/templates/signup.html
{% extends "base.html" %}


{% block title %} Register {% endblock %}

{% block nav %}
<div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
        <li class="nav-item">
            <a class="nav-link disabled" aria-current="page" href="#">Home</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="{{ url_for('auth.login') }}">Login</a>
        </li>
        <li class="nav-item">
            <a class="nav-link disabled active" href="{{ url_for('auth.signup' )}}">Register</a>
        </li>
    </ul>
</div>
{% endblock %}



{% block content %}


{% with messages = get_flashed_messages(with_categories=true) %}
{% if messages %}

{% for category, message in messages %}
<div class="container" style="max-width: 40rem;">
    <div class="alert alert-{{ category }} mt-2" role="alert">{{ message }}</div>
</div>
{% endfor %}

{% endif %}
{% endwith %}


<div class="text-center">
    <h2 class="mb-3 p-5">Sign up to get started!</h1>
</div>

<form method="post" class="container-fluid" style="max-width: 35rem;">

    <!-- email -->
    <div class="form-outline mb-4 bg-light">
        <input type="email" id="email" name="email" class="form-control" required />
        <label class="form-label" for="username">E-mail</label>
    </div>

    <!-- login -->
    <div class="form-outline mb-4 bg-light">
        <input type="text" id="username" name="username" class="form-control" required />
        <label class="form-label" for="username">Login</label>
    </div>

    <!-- password -->
    <div class="form-outline mb-4 bg-light">
        <input type="password" id="password" name="password" class="form-control" required />
        <label class="form-label" for="password">Password</label>
    </div>

    <!-- repeat password -->
    <div class="form-outline mb-6 bg-light">
        <input type="password" id="confirm-password" name="confirm_password" class="form-control" required />
        <label class="form-label" for="confirm-password">Confirm password</label>
    </div>


    <button type="submit" class="btn btn-success btn-block mb-4">Sign up</button>

    <div class="text-center">
        <p>Already a member? <a href="{{ url_for('auth.login' ) }}">Login</a></p>
    </div>
</form>




{% endblock %}